version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: online_store
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: "postgres://admin:admin@postgres:5432/online_store"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "anon"
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres-data:
