name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js and install dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # Step 3: Run Jest tests (Unit and Integration)
    - name: Run Jest tests
      run: npm test

    # Step 4: Run Cypress end-to-end tests
    - name: Run Cypress tests
      run: npx cypress run

    # Optional Step 5: Build and deploy (if needed)
    - name: Deploy application
      run: npm run deploy  # If you have a deploy script
